name: release

permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Cleanup build folder
        run: |
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect required Go version
        run: |
          toolchain=$(./script/tools.sh gotoolchain | sed 's/go*//')
          echo "GOVERSION=${toolchain}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOVERSION }}"
      - name: Setup direnv
        uses: HatsuneMiku3939/direnv-action@v1
        with:
          masks: ''
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build application
        run: |
          CGO_ENABLED=0 GO111MODULE=on go build -mod=readonly ./cmd/provider-services
      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/lumeweb/akash-provider:debug
            ghcr.io/lumeweb/akash-provider:${{ github.sha }}